### ISSUE TITLE
issue with creating files

### ISSUE THREAD

**Issue by wajwuz** [dockcenter/velocity#9]
```
[12:43:21 ERROR]: Unable to read/load/save your velocity.toml. The server will shut down.
com.electronwill.nightconfig.core.io.WritingException: An I/O error occured
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:222) ~[velocity.jar:3.1.1]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[velocity.jar:3.1.1]
        at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[velocity.jar:3.1.1]
        at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.config.VelocityConfiguration.read(VelocityConfiguration.java:414) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.VelocityServer.doStartupConfigLoad(VelocityServer.java:292) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:215) ~[velocity.jar:3.1.1]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.1]
Caused by: java.nio.file.AccessDeniedException: velocity.toml
        at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.newOutputStream(Unknown Source) ~[?:?]
        at java.nio.file.Files.copy(Unknown Source) ~[?:?]
        at com.electronwill.nightconfig.core.file.FileNotFoundAction.lambda$copyData$3(FileNotFoundAction.java:51) ~[velocity.jar:3.1.1]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:215) ~[velocity.jar:3.1.1]
```

composer:
```yaml
 proxy:
    image: dockcenter/velocity:stable
    ports: 
      - "25565:25565"
    volumes:
      - type: bind
        source: /root/proxy
        target: /data
    restart: unless-stopped
    tty: true
    stdin_open: true
```

image is not creating files in dir

**Comment by tannerstephens** [comment]
@wajwuz Not sure if you figured this out yet or not, but the issue here is that for bind volumes, the container-user "velocity" likely doesn't have permissions to write to the directory. Their UID/GID is 100:101, or you can make the directory public (Not the best idea)

**Comment by danny900714** [comment]
Yes for security issue, the user in container uses an unique non-root user to prevent privilege escalation. If you want to avoid `PERMISSION_DENIED`, make sure the velocity user has the ability to access data directory.
